export const TEST_DISPATCH = "TEST_DISPATCH";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// export const GET_PROFILE = "GET_PROFILE";
// export const PROFILE_LOADING = "PROFILE_LOADING";
// export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
// export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
// export const GET_PROFILES = "GET_PROFILES";
// export const POST_LOADING = "POST_LOADING";
// export const GET_POSTS = "GET_POSTS";
// export const GET_POST = "GET_POST";
// export const ADD_POST = "ADD_POST";
// export const DELETE_POST = "DELETE_POST";

// export const GET_ALL_THUMBNAILS = "GET_ALL_THUMBNAILS";
// export const GET_THUMBNAILS = "GET_THUMBNAILS";
// export const GET_SEARCH_THUMBNAILS = "GET_SEARCH_THUMBNAILS";
// export const GET_CATEGORY_THUMBNAILS = "GET_CATEGORY_THUMBNAILS";
// export const GET_WILDCARD_THUMBNAILS = "GET_WILDCARD_THUMBNAILS";
// export const GET_EMOTION_THUMBNAILS = "GET_EMOTION_THUMBNAILS";

// export const GET_SEARCH_THUMBNAILS = "GET_SEARCH_THUMBNAILS";
// export const GET_INDIVIDUAL_THUMBNAIL = "GET_INDIVIDUAL_THUMBNAIL";

// export const GET_STATE_SEARCH_THUMBNAILS = "GET_STATE_SEARCH_THUMBNAILS";

// export const GET_MIMES = "GET_MIMES";
// export const GET_ADMIN_MIMES = "GET_ADMIN_MIMES";

// export const FILTER_MIMES = "FILTER_MIMES";
// export const FILTER_CATEGORY_MIMES = "FILTER_CATEGORY_MIMES";
// export const GET_TRENDING = "GET_TRENDING";

// export const CREATE_MIME = "CREATE_MIME";
// export const DELETE_MIME = "DELETE_MIME";
// export const SET_CURRENT_MIME = "SET_CURRENT_MIME";
// export const MODIFY_MIME = "MODIFY_MIME";
// export const CHANGE_MIME_STATUS = "CHANGE_MIME_STATUS";
// export const SET_STATUS_MESSAGE = "SET_STATUS_MESSAGE";
// export const CLEAR_STATUS_MESSAGE = "CLEAR_STATUS_MESSAGE";
